name: Test Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Checks Test Coverage
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run test-coverage
    - name: Uploads results
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./test/coverage-jest/coverage-final.json