name: Test Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - name: Checks Test Coverage
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g jest
    - run: npm install -g yarn
    - run: yarn
    - run: yarn test:ci
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./test/coverage-jest/lcov.info
